color: null
description: null
fieldLayouts:
  2f177f8a-608f-4c2c-927b-fdbe56311e41:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-27T07:07:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: ecb78249-8ba6-43bc-98bc-dad157c791d8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T07:35:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 76b5189a-02d7-47a4-87b8-108f7e88d0a0 # Afbeelding
            handle: null
            includeInCards: false
            instructions: 'Deze wordt ook als teaser gebruikt'
            label: Headerafbeelding
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f07e0077-f947-4e49-8004-46c9eb830e22
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-27T16:35:10+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9664a544-faa7-495b-a078-abe6ffbc7468 # Tekst
            handle: null
            includeInCards: false
            instructions: null
            label: Tekst
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b2d47227-b536-41f3-9001-afed6c768f5c
            userCondition: null
            warning: null
            width: 100
        name: Header
        uid: 7134aa6f-510b-4c7d-b4d7-17677bc62802
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-09-27T07:24:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 0b2346f1-7a54-4b8f-b1b1-a4f189c53229 # Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9b050edc-cc5b-4568-9036-9f5aba5ba4ac
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: f6617e63-8e30-443b-b860-7bab4eff33d9
        userCondition: null
handle: page
hasTitleField: true
icon: null
name: Pagina
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
