altTranslationKeyFormat: null
altTranslationMethod: language
fieldLayouts:
  b36055ef-3790-4f1a-837d-9b66f288d37f:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-27T08:37:00+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: a8df7a39-9d87-45a7-b161-08eaa0ee71fe
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 0397c031-bdb3-4dea-9a4f-c0dde610da45
        userCondition: null
fs: local
handle: media
name: Media
sortOrder: 1
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: _transforms
