altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  dd7dbae4-0a9d-4f8c-b462-0badd68d1967:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-27T16:18:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: cfc9d1d0-c47f-4af0-9f8c-7c95799e5aaf
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 8b3b1173-a749-4423-86d7-90701e4697d0
        userCondition: null
fs: $DEPLOY_NAME
handle: pdfs
name: PDFs
sortOrder: 3
subpath: pdfs
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
