columnSuffix: null
handle: readTime
instructions: 'De geschatte leestijd'
name: Leestijd
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: 1
  suffix: min
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
