dateModified: 1758899368
email:
  fromEmail: admin@janhendrickx.be
  fromName: Olympus
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    02d45b6e-2da1-402a-b68d-08bd41806ef2: Olympus # Olympus
    7e871822-703c-4aca-9a68-8a32db079030: Olympus # Olympus
system:
  edition: solo
  live: true
  name: Olympus
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
