defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6c31802d-fa2a-4d5c-86e3-a1d397bbc1d6 # Pagina
handle: categories
maxAuthors: 1
name: Categorieën
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  02d45b6e-2da1-402a-b68d-08bd41806ef2: # Olympus
    enabledByDefault: true
    hasUrls: true
    template: categorie/_entry.twig
    uriFormat: 'categorie/{slug}'
  565f03de-8265-4182-9266-de1269139e81: # Olympus EN
    enabledByDefault: true
    hasUrls: true
    template: categorie/_entry.twig
    uriFormat: 'category/{slug}'
type: channel
