defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 11b249e1-d9a7-4d9d-8905-9640fe34a5b3 # Navigatie
handle: navigation
maxAuthors: 1
name: Navigatie
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  02d45b6e-2da1-402a-b68d-08bd41806ef2: # Olympus
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  565f03de-8265-4182-9266-de1269139e81: # Olympus EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 2
  uid: 0ed24f8f-d85d-4bf1-9544-b30008020670
type: structure
